#BSEF19M007 ANNS SHAHBAZ
def main(): #MAIN FUNCTION
    FTEMP = input("=> GIVE TEMPERATURE IN FAHRENHEIT: ") #FARHENHEIT INPUT
    CTEMP = Converter(FTEMP) #CONVERTING
    print("=> TEMPERATURE IN CENTIGRADE IS: ", CTEMP) #PRINTING
    
def Converter(FTEMP): #CONVERTER FUNCTION
  FTEMP = float(FTEMP) 
  CTEMP = (FTEMP - 32) * (5/9) #CONVERTING
  return CTEMP #RETURNING

main()
    

